### ISSUE TITLE
macOS: `sokol.m` vs `sokol.c` with `-ObjC`

### ISSUE THREAD

**Issue by toyboot4e** [floooh/cimgui-sokol-starterkit#5]
Hi, I [tried](https://github.com/toyboot4e/cimgui-sokol-starterkit/commit/ff9bc8422a20b74b5842aeada069310797f2479e) building with `sokol.c` and `-ObjC` flag on macOS, and it compile `demo` without errors. But I'm not sure what I'm doing actually. So let me ask a question: which is preferred, `sokol.m`  or `-ObjC` with `sokol.c`? Thank you.

**Comment by floooh** [comment]
Both should work the same, whatever you prefer is the right way ;)

Using the file extension makes it a bit easier in mixed-source libraries, because target_compile_options(...) sets the option for the entire compilation target, not just for the sokol.c file (cmake also has "set_source_files_properties" for this though). But in this specific case (just one source file in the whole library) this doesn't matter.
